In [ ]:
import numpy as np 
np.random.random((3,3))

array([[0.67907067, 0.38427354, 0.34656877],
       [0.91366832, 0.26348086, 0.54226572],
       [0.32134189, 0.53454224, 0.96715467]])

In [2]:
a = ["ali",3, "omar",False]
np.random.choice(a, size=(3, 5))

array([['3', 'False', 'False', 'omar', 'ali'],
       ['3', 'False', 'ali', 'False', 'False'],
       ['ali', 'omar', '3', 'False', 'False']], dtype='<U21')

In [3]:
Mat1 = np.ones((3,4))
Mat2 = np.zeros((5,3))
np.savez('file.npz', Ones_Mat=Mat1, Zeros_Mat=Mat2)

In [6]:
with np.load('file.npz') as file:
    Mat1 = file['Ones_Mat']
    Mat2 = file['Zeros_Mat']
print(Mat1)
print("---------------")
print(Mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
---------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([2, 3, 4, 5, 6])
np.allclose(v1, v2, atol=1)

True

In [8]:
v = np.array([2, 4, 3, 4, 10])
condition = v >= 4
print(condition)

[False  True False  True  True]


In [12]:
import pandas as pd

In [ ]:
import pandas as pd 
x = pd.Series([1,2,3,4,5,6,7,8,9,10], index = ['a','b','c',])
type(x)

pandas.Series