In [ ]:
import numpy as np 
np.random.random((3,3))

array([[0.67907067, 0.38427354, 0.34656877],
       [0.91366832, 0.26348086, 0.54226572],
       [0.32134189, 0.53454224, 0.96715467]])

In [2]:
a = ["ali",3, "omar",False]
np.random.choice(a, size=(3, 5))

array([['3', 'False', 'False', 'omar', 'ali'],
       ['3', 'False', 'ali', 'False', 'False'],
       ['ali', 'omar', '3', 'False', 'False']], dtype='<U21')

In [3]:
Mat1 = np.ones((3,4))
Mat2 = np.zeros((5,3))
np.savez('file.npz', Ones_Mat=Mat1, Zeros_Mat=Mat2)

In [6]:
with np.load('file.npz') as file:
    Mat1 = file['Ones_Mat']
    Mat2 = file['Zeros_Mat']
print(Mat1)
print("---------------")
print(Mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
---------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([2, 3, 4, 5, 6])
np.allclose(v1, v2, atol=1)

True

In [8]:
v = np.array([2, 4, 3, 4, 10])
condition = v >= 4
print(condition)

[False  True False  True  True]


In [12]:
import pandas as pd

In [ ]:
import pandas as pd 
x = pd.Series([1,2,3,4,5,6,7,8,9,10], index = ['a','b','c',])
type(x)

pandas.Series

In [ ]:
cols = ['coll']

In [2]:
data = [[1,444,"abc"], [2,555,"def"],[3,666,"ghi"],[4,444,"xyz"]]

In [7]:
import pandas as pd 
df = pd.DataFrame(data,columns=['col1','cols2','cols3'])

In [9]:
cols = ['id','sal']
df['id'] = df['id'].astype('category')
df.dtypes

KeyError: 'id'

In [10]:
df.describe()

,col1,cols2
count,4.000000,4.000000
mean,2.500000,527.250000
std,1.290994,106.274409
min,1.000000,444.000000
25%,1.750000,444.000000
50%,2.500000,499.500000
75%,3.250000,582.750000
max,4.000000,666.000000


In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   cols2   4 non-null      int64
 2   cols3   4 non-null      str  
dtypes: int64(2), str(1)
memory usage: 228.0 bytes


In [11]:
df.describe(include='category')

ValueError: No columns match the specified include or exclude data types

In [13]:
df.col1.iloc[2]

np.int64(3)

In [14]:
df.col1.iloc[0:2]

0    1
1    2
Name: col1, dtype: int64

In [15]:
df.iloc[2, 1]

np.int64(666)

In [ ]:
df.iloc[:, ]